from __future__ import annotations

import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "SKILL.md"
SCENARIOS = (ROOT / "tests" / "scenarios.yaml").read_text(encoding="utf-8")


def normalized() -> str:
    return " ".join(SKILL.read_text(encoding="utf-8").lower().replace("`", "").split())


class DocusaurusStandardsContractTests(unittest.TestCase):
    def test_frontmatter_trigger(self):
        text = SKILL.read_text(encoding="utf-8")
        self.assertTrue(text.startswith("---\nname: core-development-docusaurus-standards\n"))
        description = re.search(r"^description: (.+)$", text, re.MULTILINE).group(1).lower()
        for phrase in ("docusaurus-specific", "seo", "do not use", "another documentation generator"):
            self.assertIn(phrase, description)

    def test_entrypoint_is_concise(self):
        text = SKILL.read_text(encoding="utf-8")
        self.assertLessEqual(len(text.splitlines()), 130)
        self.assertLessEqual(len(text.split()), 1500)

    def test_original_contract_is_literal(self):
        text = SKILL.read_text(encoding="utf-8")
        for phrase in (
            "Organize docs into clear sections with sidebar structure.",
            "Use `docs/` folder with `sidebars.js` or `sidebars.ts`.",
            "Write in Markdown/MDX; keep docs concise and structured.",
            "Apply SEO tags and metadata for each page.",
            "Version documentation for major releases.",
            "Deploy docs via CI/CD pipeline; validate links and build.",
        ):
            self.assertIn(phrase, text)

    def test_complete_contract_and_authority(self):
        text = normalized()
        for phrase in (
            "complete site graph",
            "mdx can execute javascript",
            "require explicit authority",
            "confirm exact artifact and target",
            "stable public routes",
        ):
            self.assertIn(phrase, text)

    def test_structure_contracts(self):
        text = normalized()
        for phrase in (
            "audience tasks",
            "custom paths and multiple plugin instances",
            "explicit, autogenerated, or mixed sidebars",
            "doc id, route slug, file path",
            "route redirect does not alias a changed #fragment",
            "legacy explicit heading ids",
            "compatibility window",
        ):
            self.assertIn(phrase, text)

    def test_mdx_and_metadata_safety(self):
        text = normalized()
        for phrase in (
            "mdx only when interaction",
            "safe for server rendering",
            "canonical route",
            "metadata presence alone",
            "private urls",
        ):
            self.assertIn(phrase, text)

    def test_version_and_delivery_boundaries(self):
        text = normalized()
        for phrase in (
            "every major release as a mandatory documentation-versioning decision",
            "evidence-backed not-applicable decision",
            "tag alone does not prove",
            "current and every supported version",
            "bounded timeouts and retries",
            "policy-blocked checks",
            "repository-pinned dependency graph",
            "broken internal links and anchors",
            "already-clean isolated checkout",
            "never clean, reset, overwrite, or switch",
            "promote the verified immutable artifact",
        ):
            self.assertIn(phrase, text)

    def test_publication_receipt_is_complete(self):
        text = normalized()
        for phrase in ("exact publication target", "observed indexing eligibility or status"):
            self.assertIn(phrase, text)

    def test_evidence_states(self):
        text = normalized()
        for phrase in (
            "edited source",
            "parsed content",
            "successful build",
            "link-check result",
            "previewed artifact",
            "deployed revision",
            "indexed page",
            "healthy public site",
        ):
            self.assertIn(phrase, text)

    def test_scenarios(self):
        blocks = re.split(r"(?=^  - id: )", SCENARIOS, flags=re.MULTILINE)[1:]
        self.assertEqual(len(blocks), 28)
        ids, expectations = [], set()
        for block in blocks:
            identifier = re.search(r"^  - id: (.+)$", block, re.MULTILINE).group(1)
            fields = dict(re.findall(r"^    (expect|prompt|evidence): (.+)$", block, re.MULTILINE))
            self.assertEqual(set(fields), {"expect", "prompt", "evidence"})
            self.assertGreaterEqual(len(fields["prompt"].split()), 7)
            self.assertGreaterEqual(len(fields["evidence"].split()), 8)
            ids.append(identifier)
            expectations.add(fields["expect"])
        self.assertEqual(len(ids), len(set(ids)))
        self.assertEqual(expectations, {"trigger", "no_trigger", "safe_behavior", "bounded_behavior", "workflow"})


if __name__ == "__main__":
    unittest.main()
